"""update_ocean_data_table

Revision ID: 187d4dd02f7e
Revises: b23dedb5d584
Create Date: 2026-08-04 23:03:58.387895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187d4dd02f7e'
down_revision: Union[str, Sequence[str], None] = 'b23dedb5d584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocean_data', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('ocean_data', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('ocean_data', sa.Column('salinity', sa.Float(), nullable=False))
    op.add_column('ocean_data', sa.Column('oxygen', sa.Float(), nullable=False))
    op.add_column('ocean_data', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('ocean_data', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ocean_data', 'ph',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ocean_data', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ocean_data', 'location')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('ocean_data', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('ocean_data', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ocean_data', 'ph',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ocean_data', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('ocean_data', 'created_at')
    op.drop_column('ocean_data', 'oxygen')
    op.drop_column('ocean_data', 'salinity')
    op.drop_column('ocean_data', 'longitude')
    op.drop_column('ocean_data', 'latitude')
    # ### end Alembic commands ###
