"""create sos requests

Revision ID: 54891b6527e7
Revises: de9d6fb29614
Create Date: 2026-08-08 19:23:28.327982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54891b6527e7'
down_revision: Union[str, Sequence[str], None] = 'de9d6fb29614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sos_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['ocean_data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_requests_id'), 'sos_requests', ['id'], unique=False)
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_sensor_devices_device_id'), table_name='sensor_devices')
    op.drop_index(op.f('ix_sensor_devices_id'), table_name='sensor_devices')
    op.drop_table('sensor_devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('firmware_version', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('battery_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('sensor_devices_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sensor_devices_pkey'))
    )
    op.create_index(op.f('ix_sensor_devices_id'), 'sensor_devices', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_devices_device_id'), 'sensor_devices', ['device_id'], unique=True)
    op.create_table('sensor_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sensor_device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('salinity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('oxygen', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('water_quality', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sensor_device_id'], ['sensor_devices.id'], name=op.f('sensor_readings_sensor_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sensor_readings_pkey'))
    )
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.drop_index(op.f('ix_sos_requests_id'), table_name='sos_requests')
    op.drop_table('sos_requests')
    # ### end Alembic commands ###
